name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn build

      - name: Print working directory
        run: echo "Working directory is $(pwd)"

      - name: Checkout Repository
        uses: actions/checkout@v3

  # Deploy development
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ vars.REMOTE_PATH }}

  # Deploy staging
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.URL }}
    needs: deploy-development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ vars.REMOTE_PATH }}

  # Deploy production
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.URL }}
    needs: deploy-staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ vars.REMOTE_PATH }}
