name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm install 

      - name: Build
        run: npm run build

  # Deploy development
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "cd sap_frontend dist/"  
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "./domains/ti-gruposantin.com.br/public_html/dev/"  

  # Deploy staging
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.URL }}
    needs: [build, deploy-development]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "cd sap_frontend dist/"  
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "./domains/ti-gruposantin.com.br/public_html/stage/" 

  # Deploy production
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.URL }}
    needs: [build, deploy-staging]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_HOSTINGER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "cd sap_frontend dist/" 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "./domains/ti-gruposantin.com.br/public_html/"  
